### ISSUE TITLE
fix automatic pursuit publication

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-unfoldable#18]
pursuit doesn't include recent releases: https://pursuit.purescript.org/packages/purescript-unfoldable/3.0.0

**Comment by matthewleon** [comment]
(or rather, it doesn't have the latest)

**Comment by garyb** [comment]
This should be fixed when we do the next publish: https://github.com/purescript/purescript-unfoldable/commit/21bd8719ad8f9125d9986fc3b419f9352f02df9a
