### ISSUE TITLE
UnfoldableWithIndex

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-unfoldable#21]
Any thoughts on this? It makes sense to me.

**Comment by paf31** [comment]
Do you have a suggested API?

**Comment by matthewleon** [comment]
I would intuitively think something like

```purescript
class UnfoldableWithIndex i f | f -> i where
  unfoldrWithIndex 
    :: forall a b
     . Monoid a 
    => (b -> Maybe (Tuple (Tuple i a) b)) -> b -> f a
```

Of course, `Maybe (Tuple (Tuple i a) b)` is ugly, so you'd probably want to define something a nicer than that.

I guess the utility of this is really mitigated by `Map` having the `Ord` constraint. Not sure what to think about that.

**Comment by paf31** [comment]
So this is for things like `Map` and not things like `Array` then?

**Comment by matthewleon** [comment]
On the contrary, the only types in core that I could see implementing this would be `Array` and `List` (horribly inefficient, though).

**Comment by paf31** [comment]
What would the index types for those be? `Unit`?

**Comment by paf31** [comment]
I'm also not keen on the `Monoid a` constraint there.

**Comment by matthewleon** [comment]
> What would the index types for those be? Unit?

`Int`, no? The idea being that this is a dual of `FoldableWithIndex`.

> I'm also not keen on the Monoid a constraint there.

Ideally I think it'd be a `Semigroup`... But then in the case of datatypes that can be left "sparse", you need some way to tell them what the default value is. Maybe the solution is to just have it be `Semigroup`, and then use `newtype`s.

**Comment by matthewleon** [comment]
> What would the index types for those be? Unit?
> 
> Int, no? The idea being that this is a dual of FoldableWithIndex.

To elaborate, for `Array` this provides a way of building an `Array` through accumulation, where the index/value pairs can come in out of order.

**Comment by paf31** [comment]
Out of order but also incomplete, right? That seems bad.

**Comment by matthewleon** [comment]
> Out of order but also incomplete, right? That seems bad.

Yes, that's why I opted for `Monoid`.

Not sure if there is a really satisfying solution.

**Comment by hdgarrood** [comment]
I'm going to close this for now as this seems to have stalled, and there doesn't seem to be a good solution to the incompleteness issue.
